### ISSUE TITLE
TextRender rotation: visible for owner only

### ISSUE THREAD

**Issue by OnlineCop** [nolcay/Centrifugal#1]
For a networked game, this is fairly simple since the TextRender rotation is not replicated. For this split-screen setup, however, I ended up doing the following:

Gallery: https://imgur.com/a/QSjVg

1. Duplicate BillboardTextBP for each/both players: `BillboardTextBP_P1` and `BillboardTextBP_P2`
2. Inside BillboardTextBP's Tick event, rotate the TextRender toward the BP's owner.
![BillboardTextBP::Tick](https://i.imgur.com/SBIrzkl.png)
3. While in BillboardTextBP, select the TextRender and (in the `Details` window) expand the `Rendering` area. Select the `Only Owner See` option.
4. Inside GamemodeBP's BeginPlay event, assign owners for both BillboardTextBP instances: one to each PlayerBP
![GamemodeBP::BeginPlay](https://i.imgur.com/vA98eSU.png)

As you can see, the text rotates toward the player, and only the player's own TextRender is seen in each camera:
![PIE](https://i.imgur.com/lTrq1pa.png)

One problem with this setup is you may want multiple BillboardTextBPs scattered throughout the level. You may be able to do this easily by adding an `OwnedByPlayer1` or `OwnedByPlayer2` tag to all the TextRenders, and searching for all BillboardTextBP objects that contain the correct tag. That way, you can set all of the Owners at the same time in BeginPlay, no matter how many of them you have in the level.

Another problem is that you'll want to update both TextRenders at once to show the same text. Since objects can contain multiple tags, you can add a second tag to each TextRender pair and use the same search-by-tag to find the right tags and updating their text values.

**Comment by nolcay** [comment]
Cool! It would be nice if you could open a pull request when you finish up. Thanks!

**Comment by OnlineCop** [comment]
Do you want the text to face the ball? The camera? Do you want it to just face forward (in `BeginPlay`) but not rotate real-time (in `Tick`)?

Will you ever have 1, 3 or 4 players, or will it always be 2?

**Comment by nolcay** [comment]
For it to face the camera would be preferable. The player count should be dynamic, but for that you could just take the length of GetAllActorsInClass

**Comment by OnlineCop** [comment]
I've been looking into a more flexible solution for this, although it requires an array of owners to be sent to each of these BPs so it can dynamically create TextRender actors for each. 

That would allow each TextRender to rotate toward its owner with an Only Owner See to prevent all other cameras from displaying them.

**Comment by OnlineCop** [comment]
Your current code has Player1 and Player2 variables set all over the place, which would have to be converted into arrays if you wanted to allow a more dynamic number of simultaneous players.

**Comment by OnlineCop** [comment]
Cloned into https://github.com/OnlineCop/Centrifugal, but not ready to push yet. I've been reorganizing all the methods to clean them up, and trying to shove the P1 and P2 variables into arrays.

Once that's done, the BillboardTextBP should be able to be set with the number of players (1, 2, 4, etc.) which would spawn 4 separate TextRenders and have each of them face the appropriate camera.

The process is a bit slow, though. And most likely, the logic has been broken and will need to be fixed before it's ready to be pull-requested.

**Comment by nolcay** [comment]
Thanks for helping me out with this project! I appreciate that a lot. I can probably merge and continue working on the game a couple of days later.
